### ISSUE TITLE
[BUG🐛] ModuleNotFoundError: No module named 'langid'

### ISSUE THREAD

**Issue by zzfoo** [astramind-ai/Auralis#36]
## Bug Description
When trying to use the Auralis library, the code fails with a `ModuleNotFoundError` because the required dependency `langid` is not installed. The `langid` package is a dependency of Auralis but is not automatically installed when installing Auralis through pip.

## Minimal Reproducible Example
```bash
$ conda create -n auralis python=3.10
$ conda activate auralis
$ pip install auralis
```

``` python
from auralis import TTS, TTSRequest

tts = TTS().from_pretrained("AstraMindAI/xttsv2", gpt_model='AstraMindAI/xtts2-gpt')

request = TTSRequest(
    text="Hello Earth! This is Auralis speaking.",
    speaker_files=['reference.wav']
)

output = tts.generate_speech(request)
output.save('hello.wav')
```
## Error Logs
```
$ python main.py
Traceback (most recent call last):
  File "C:\work\tools\auralis\main.py", line 1, in <module>
    from auralis import TTS, TTSRequest
  File "C:\Users\Administrator\miniconda3\envs\auralis\lib\site-packages\auralis\__init__.py", line 1, in <module>
    from .core.tts import TTS
  File "C:\Users\Administrator\miniconda3\envs\auralis\lib\site-packages\auralis\core\tts.py", line 16, in <module>
    from auralis.common.definitions.requests import TTSRequest
  File "C:\Users\Administrator\miniconda3\envs\auralis\lib\site-packages\auralis\common\definitions\requests.py", line 8, in <module>
    import langid
ModuleNotFoundError: No module named 'langid'
```

**Comment by kwaa** [comment]
Also mentioned here: https://github.com/astramind-ai/Auralis/pull/26#issuecomment-2519655749

As a temporary solution, you can use `pip install langid auralis`.
