### ISSUE TITLE
I installed Auralis on Windows 10, but it has an error. Vllm

### ISSUE THREAD

**Issue by kerlynla** [astramind-ai/Auralis#51]
Who can guide me install it ?
Thank you very much

(H:\Auralis-0.2.8.post2\env-cuda12.1) H:\Auralis-0.2.8.post2>python run.py
Traceback (most recent call last):
  File "H:\Auralis-0.2.8.post2\run.py", line 1, in <module>
    from auralis import TTS, TTSRequest
  File "H:\Auralis-0.2.8.post2\env-cuda12.1\lib\site-packages\auralis\__init__.py", line 1, in <module>
    from .core.tts import TTS
  File "H:\Auralis-0.2.8.post2\env-cuda12.1\lib\site-packages\auralis\core\tts.py", line 18, in <module>
    from auralis.models.base import BaseAsyncTTSEngine, AudioOutputGenerator
  File "H:\Auralis-0.2.8.post2\env-cuda12.1\lib\site-packages\auralis\models\__init__.py", line 1, in <module>
    from .xttsv2 import XTTSv2Engine
  File "H:\Auralis-0.2.8.post2\env-cuda12.1\lib\site-packages\auralis\models\xttsv2\__init__.py", line 1, in <module>
    from .XTTSv2 import XTTSv2Engine
  File "H:\Auralis-0.2.8.post2\env-cuda12.1\lib\site-packages\auralis\models\xttsv2\XTTSv2.py", line 17, in <module>
    from vllm import AsyncLLMEngine, AsyncEngineArgs, TokensPrompt, RequestOutput
ImportError: cannot import name 'AsyncLLMEngine' from 'vllm' (unknown location)

**Comment by GiacomoLeoneMaria** [comment]
The problem seems to be related to the `vllm` package. Possible causes include:

1. **vLLM is not installed.**
   - Ensure the `vllm` package is installed in your environment.
2. **Version mismatch between Auralis and its required vLLM version.**
   - Verify that the version of `vllm` installed is compatible with Auralis.
   - Update or downgrade `vllm` as necessary to match the requirements.

**Which version of `vllm` are you using?**  
You should have `vllm==0.6.4.post1`.  

Check the installed version of `vllm`:
   ```bash
   pip show vllm
   pip freeze | grep vllm
